# Generated by Django 4.2.7 on 2023-11-19 10:41

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='books/image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/', validators=[books.models.validate_pdf_file]),
        ),
    ]
